# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'languages-2.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 20, 861, 491))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 10, 101, 22))
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 40, 91, 22))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 70, 101, 22))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 100, 88, 22))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 130, 101, 22))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 160, 111, 22))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 190, 88, 22))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 220, 111, 22))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 250, 88, 22))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 280, 88, 22))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 310, 101, 22))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 340, 88, 22))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 370, 88, 22))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_15.setGeometry(QtCore.QRect(10, 400, 101, 22))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 430, 88, 22))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_17.setGeometry(QtCore.QRect(140, 10, 88, 22))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 460, 88, 22))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_19.setGeometry(QtCore.QRect(140, 40, 88, 22))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_20.setGeometry(QtCore.QRect(140, 70, 88, 22))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_21.setGeometry(QtCore.QRect(140, 100, 88, 22))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_22.setGeometry(QtCore.QRect(140, 130, 88, 22))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_23.setGeometry(QtCore.QRect(140, 160, 101, 22))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_24.setGeometry(QtCore.QRect(140, 190, 88, 22))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_25.setGeometry(QtCore.QRect(140, 220, 88, 22))
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_26.setGeometry(QtCore.QRect(140, 250, 88, 22))
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_27.setGeometry(QtCore.QRect(140, 280, 88, 22))
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_29 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_29.setGeometry(QtCore.QRect(140, 340, 88, 22))
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_30.setGeometry(QtCore.QRect(140, 370, 88, 22))
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_31 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_31.setGeometry(QtCore.QRect(140, 400, 88, 22))
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_32.setGeometry(QtCore.QRect(140, 430, 88, 22))
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_33 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_33.setGeometry(QtCore.QRect(140, 460, 88, 22))
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_34.setGeometry(QtCore.QRect(270, 10, 88, 22))
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_35 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_35.setGeometry(QtCore.QRect(270, 40, 88, 22))
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_36.setGeometry(QtCore.QRect(270, 70, 88, 22))
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_37.setGeometry(QtCore.QRect(270, 100, 88, 22))
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_38.setGeometry(QtCore.QRect(270, 130, 88, 22))
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_39.setGeometry(QtCore.QRect(270, 160, 88, 22))
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_40.setGeometry(QtCore.QRect(270, 190, 88, 22))
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_41.setGeometry(QtCore.QRect(270, 220, 88, 22))
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_42.setGeometry(QtCore.QRect(270, 250, 88, 22))
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_43.setGeometry(QtCore.QRect(270, 280, 88, 22))
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_44.setGeometry(QtCore.QRect(270, 310, 88, 22))
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_45 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_45.setGeometry(QtCore.QRect(270, 340, 88, 22))
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkBox_46 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_46.setGeometry(QtCore.QRect(270, 370, 88, 22))
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkBox_47 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_47.setGeometry(QtCore.QRect(270, 400, 88, 22))
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_48 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_48.setGeometry(QtCore.QRect(270, 430, 88, 22))
        self.checkBox_48.setObjectName("checkBox_48")
        self.checkBox_49 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_49.setGeometry(QtCore.QRect(270, 460, 88, 22))
        self.checkBox_49.setObjectName("checkBox_49")
        self.checkBox_50 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_50.setGeometry(QtCore.QRect(400, 10, 88, 22))
        self.checkBox_50.setObjectName("checkBox_50")
        self.checkBox_51 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_51.setGeometry(QtCore.QRect(400, 40, 88, 22))
        self.checkBox_51.setObjectName("checkBox_51")
        self.checkBox_52 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_52.setGeometry(QtCore.QRect(400, 70, 88, 22))
        self.checkBox_52.setObjectName("checkBox_52")
        self.checkBox_53 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_53.setGeometry(QtCore.QRect(400, 100, 88, 22))
        self.checkBox_53.setObjectName("checkBox_53")
        self.checkBox_54 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_54.setGeometry(QtCore.QRect(400, 130, 88, 22))
        self.checkBox_54.setObjectName("checkBox_54")
        self.checkBox_55 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_55.setGeometry(QtCore.QRect(400, 160, 88, 22))
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_56 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_56.setGeometry(QtCore.QRect(400, 190, 88, 22))
        self.checkBox_56.setObjectName("checkBox_56")
        self.checkBox_57 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_57.setGeometry(QtCore.QRect(400, 220, 88, 22))
        self.checkBox_57.setObjectName("checkBox_57")
        self.checkBox_58 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_58.setGeometry(QtCore.QRect(400, 250, 88, 22))
        self.checkBox_58.setObjectName("checkBox_58")
        self.checkBox_59 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_59.setGeometry(QtCore.QRect(400, 280, 88, 22))
        self.checkBox_59.setObjectName("checkBox_59")
        self.checkBox_60 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_60.setGeometry(QtCore.QRect(400, 310, 88, 22))
        self.checkBox_60.setObjectName("checkBox_60")
        self.checkBox_61 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_61.setGeometry(QtCore.QRect(400, 340, 88, 22))
        self.checkBox_61.setObjectName("checkBox_61")
        self.checkBox_62 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_62.setGeometry(QtCore.QRect(400, 370, 88, 22))
        self.checkBox_62.setObjectName("checkBox_62")
        self.checkBox_63 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_63.setGeometry(QtCore.QRect(400, 400, 88, 22))
        self.checkBox_63.setObjectName("checkBox_63")
        self.checkBox_64 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_64.setGeometry(QtCore.QRect(400, 430, 88, 22))
        self.checkBox_64.setObjectName("checkBox_64")
        self.checkBox_65 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_65.setGeometry(QtCore.QRect(400, 460, 88, 22))
        self.checkBox_65.setObjectName("checkBox_65")
        self.checkBox_66 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_66.setGeometry(QtCore.QRect(520, 10, 88, 22))
        self.checkBox_66.setObjectName("checkBox_66")
        self.checkBox_67 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_67.setGeometry(QtCore.QRect(520, 40, 88, 22))
        self.checkBox_67.setObjectName("checkBox_67")
        self.checkBox_68 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_68.setGeometry(QtCore.QRect(520, 70, 88, 22))
        self.checkBox_68.setObjectName("checkBox_68")
        self.checkBox_69 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_69.setGeometry(QtCore.QRect(520, 100, 88, 22))
        self.checkBox_69.setObjectName("checkBox_69")
        self.checkBox_70 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_70.setGeometry(QtCore.QRect(520, 130, 88, 22))
        self.checkBox_70.setObjectName("checkBox_70")
        self.checkBox_71 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_71.setGeometry(QtCore.QRect(520, 160, 88, 22))
        self.checkBox_71.setObjectName("checkBox_71")
        self.checkBox_72 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_72.setGeometry(QtCore.QRect(520, 190, 88, 22))
        self.checkBox_72.setObjectName("checkBox_72")
        self.checkBox_73 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_73.setGeometry(QtCore.QRect(520, 220, 88, 22))
        self.checkBox_73.setObjectName("checkBox_73")
        self.checkBox_74 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_74.setGeometry(QtCore.QRect(520, 250, 88, 22))
        self.checkBox_74.setObjectName("checkBox_74")
        self.checkBox_75 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_75.setGeometry(QtCore.QRect(520, 280, 88, 22))
        self.checkBox_75.setObjectName("checkBox_75")
        self.checkBox_76 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_76.setGeometry(QtCore.QRect(520, 310, 88, 22))
        self.checkBox_76.setObjectName("checkBox_76")
        self.checkBox_77 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_77.setGeometry(QtCore.QRect(520, 340, 88, 22))
        self.checkBox_77.setObjectName("checkBox_77")
        self.checkBox_78 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_78.setGeometry(QtCore.QRect(520, 370, 88, 22))
        self.checkBox_78.setObjectName("checkBox_78")
        self.checkBox_79 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_79.setGeometry(QtCore.QRect(520, 400, 88, 22))
        self.checkBox_79.setObjectName("checkBox_79")
        self.checkBox_80 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_80.setGeometry(QtCore.QRect(520, 430, 88, 22))
        self.checkBox_80.setObjectName("checkBox_80")
        self.checkBox_81 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_81.setGeometry(QtCore.QRect(520, 460, 88, 22))
        self.checkBox_81.setObjectName("checkBox_81")
        self.checkBox_82 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_82.setGeometry(QtCore.QRect(630, 10, 88, 22))
        self.checkBox_82.setObjectName("checkBox_82")
        self.checkBox_83 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_83.setGeometry(QtCore.QRect(630, 40, 88, 22))
        self.checkBox_83.setObjectName("checkBox_83")
        self.checkBox_84 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_84.setGeometry(QtCore.QRect(630, 70, 88, 22))
        self.checkBox_84.setObjectName("checkBox_84")
        self.checkBox_85 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_85.setGeometry(QtCore.QRect(630, 100, 88, 22))
        self.checkBox_85.setObjectName("checkBox_85")
        self.checkBox_86 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_86.setGeometry(QtCore.QRect(630, 130, 88, 22))
        self.checkBox_86.setObjectName("checkBox_86")
        self.checkBox_87 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_87.setGeometry(QtCore.QRect(630, 160, 88, 22))
        self.checkBox_87.setObjectName("checkBox_87")
        self.checkBox_88 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_88.setGeometry(QtCore.QRect(630, 190, 88, 22))
        self.checkBox_88.setObjectName("checkBox_88")
        self.checkBox_89 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_89.setGeometry(QtCore.QRect(630, 220, 97, 22))
        self.checkBox_89.setObjectName("checkBox_89")
        self.checkBox_90 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_90.setGeometry(QtCore.QRect(630, 250, 97, 22))
        self.checkBox_90.setObjectName("checkBox_90")
        self.checkBox_91 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_91.setGeometry(QtCore.QRect(630, 280, 97, 22))
        self.checkBox_91.setObjectName("checkBox_91")
        self.checkBox_92 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_92.setGeometry(QtCore.QRect(630, 370, 97, 22))
        self.checkBox_92.setObjectName("checkBox_92")
        self.checkBox_93 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_93.setGeometry(QtCore.QRect(630, 430, 97, 22))
        self.checkBox_93.setObjectName("checkBox_93")
        self.checkBox_94 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_94.setGeometry(QtCore.QRect(630, 460, 97, 22))
        self.checkBox_94.setObjectName("checkBox_94")
        self.checkBox_95 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_95.setGeometry(QtCore.QRect(630, 400, 97, 22))
        self.checkBox_95.setObjectName("checkBox_95")
        self.checkBox_96 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_96.setGeometry(QtCore.QRect(630, 340, 97, 22))
        self.checkBox_96.setObjectName("checkBox_96")
        self.checkBox_97 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_97.setGeometry(QtCore.QRect(630, 310, 97, 22))
        self.checkBox_97.setObjectName("checkBox_97")
        self.checkBox_98 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_98.setGeometry(QtCore.QRect(730, 10, 88, 22))
        self.checkBox_98.setObjectName("checkBox_98")
        self.checkBox_99 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_99.setGeometry(QtCore.QRect(730, 40, 88, 22))
        self.checkBox_99.setObjectName("checkBox_99")
        self.checkBox_100 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_100.setGeometry(QtCore.QRect(730, 70, 88, 22))
        self.checkBox_100.setObjectName("checkBox_100")
        self.checkBox_101 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_101.setGeometry(QtCore.QRect(730, 100, 88, 22))
        self.checkBox_101.setObjectName("checkBox_101")
        self.checkBox_102 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_102.setGeometry(QtCore.QRect(730, 130, 88, 22))
        self.checkBox_102.setObjectName("checkBox_102")
        self.checkBox_104 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_104.setGeometry(QtCore.QRect(730, 160, 88, 22))
        self.checkBox_104.setObjectName("checkBox_104")
        self.checkBox_105 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_105.setGeometry(QtCore.QRect(730, 190, 88, 22))
        self.checkBox_105.setObjectName("checkBox_105")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 530, 91, 33))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        langname = open("langs.txt", "r").readlines()
        usinglangs = open("names.txt", "r").readlines()
        num = 0
        for chk in self.__dict__.items():
            if "checkBox" in str(chk[0]):
                chk[1].setText("{0}".format(str(langname[num]).split("|")[1]))
                for ulang in usinglangs:
                    tulang = "checkBox_{0}".format(ulang.split("|")[0])
                    if str(chk[0]) == str(tulang):
                        chk[1].setChecked(True)
                num = num + 1
                if num == 28:
                    num = num + 1
        self.pushButton_2.setText("Save")
